environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6
    - nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - npm set fetch-retry-maxtimeout 180000
  - curl -L https://unpkg.com/@pnpm/self-installer@1.16.2 | node
  # Testing whether pnpm can upgrade itself
  - pnpm i -g pnpm@next
  - pnpm -v
  - pnpm install
  - pnpm install --prefix .scripts/self-installer
  - pnpm install --prefix test
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - node --version
  - npm --version
  - npm t
