packages:
  - packages/**
  - privatePackages/**
  - tools/**
  - utils/**
  - "!**/__package_previews__/**"
  - "!**/example/**"
  - "!**/test/**"
  - "!packages/dependencies-hierarchy/fixtures/**"
  - "!packages/dependencies-hierarchy/fixtureWithLinks/**"
