packages:
  - tools/**
  - packages/**
  - privatePackages/**
  - "!**/store/**"
  - "!**/test/**"
  - "!**/__package_previews__/**"
  - "!packages/dependencies-hierarchy/example/**"
  - "!packages/list/example/**"
