name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install pnpm and npm
        run: |
          curl -L https://get.pnpm.io/v6.js | node - add --global pnpm@next npm@7
      - name: pnpm install
        run: pnpm install
      - name: Build Artifacts
        run: pnpm run compile && pnpm run copy-artifacts
      - name: Create deb package
        uses: skynet-core/nfpm@v1.5
        with:
          config: "utils/nfpm-configs/amd64.yaml"
          packager: "deb"
          target: "./dist/pnpm-amd64.deb"
      - name: Generate release description
        run: pnpm run make-release-description
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: dist/*
          body_path: RELEASE.md
